version: '3'
services:

  keelson-connector-mavlink:
    build: .
    # image: ghcr.io/mo-rise/keelson-connector-mavlink:latest (To be used when not developing)
    container_name: keelson-connector-mavlink
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    command: "-r rise -e masslab --device-id /dev/ttyACM0 --log-level 10"
    
