version: '3'
services:

  keelson-connector-mavlink:
    build: .
    # image: ghcr.io/mo-rise/keelson-connector-mavlink:latest (To be used when not developing)
    container_name: keelson-connector-mavlink
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # command: 
    #   [
    #     # "ls"
    #     "python3 bin/main.py -r rise -e masslab -di dev --log-level 10 -sub start"
    #   ]
