version: '3'
services:

  keelson-connector-mavlink:
    build: .
    # image: ghcr.io/mo-rise/keelson-connector-mavlink:latest (To be used when not developing)
    container_name: keelson-connector-mavlink
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: 
      [
        "python3 mavlink -r ${RELAM_ID} -kv 0 -e entity_id"
      ]
